In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

numpy is just a library in python.. look abit similar to list, but way better than list bcox it did more work than it..
pandas 
matplot

In [2]:
import numpy as np 
#this doesnt means you are downloading it.. it rather means u are asking for it to bring it into ur notebook
#data element in numpy are refers to as array
#one row is an array.. while multiple is metrix
#first row fifth column (b[1,5]).. that is the first thing that goes in is row, the second is column

In [3]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [4]:
#to get the shape
a.shape

(4,)

In [5]:
#to know how many dimension you have
a.ndim

1

In [6]:
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
b.ndim

2

In [8]:
b.shape

(2, 4)

In [9]:
b[1,2]

np.int64(7)

In [10]:
#three dimensional matrix

c = np.array([[[1, 2, 3], 
               [4, 5, 6], 
               [7, 8, 9]]])
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [11]:
c.shape

(1, 3, 3)

In [12]:
c.ndim

3

In [13]:
d = np.array([[1, 2, 3], 
               [4, 5, 6], 
                  [10, 11, 12], 
                 [13, 14, 15], 
                 [7, 8, 9]])
d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 11, 12],
       [13, 14, 15],
       [ 7,  8,  9]])

In [14]:
d.shape

(5, 3)

In [15]:
d[2,2]

np.int64(12)

In [16]:
#get a specific row

d[1]

array([4, 5, 6])

In [17]:
d[1,:]

array([4, 5, 6])

In [18]:
#get sepecific column

d[ :,1]

array([ 2,  5, 11, 14,  8])

In [19]:
d[0,1:6]

array([2, 3])

In [20]:
e = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20], [21, 22, 23, 24, 25], [26, 27, 28, 29, 30]])
e

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [21]:
e[[0, 4, 5], 3:]


array([[ 4,  5],
       [24, 25],
       [29, 30]])

In [22]:
e[[0, 1, 2, 3], [1, 2, 3, 4]]

array([ 2,  8, 14, 20])

In [23]:
#to move step
a[2:4,0:2]
b[0,1:6;2]

SyntaxError: invalid syntax (1090367529.py, line 3)

initializing arrays


In [ ]:
#all zero

np.zeros((3,5))

In [ ]:
np.ones((2,4))

In [ ]:
np.full((3,5),24)

In [ ]:
#random decimal numbers

np.random.rand(4,2)

In [24]:
#rabdom int numbers

np.random.randint(1,6, size=(5,6))

array([[4, 3, 4, 1, 5, 3],
       [2, 4, 5, 3, 1, 4],
       [2, 5, 4, 4, 4, 4],
       [4, 4, 1, 4, 4, 3],
       [2, 2, 5, 5, 5, 2]])

In [33]:
#5x5 array od ones
one = np.ones((5,5))
print(one)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [36]:
#3x3 array of zeros
zero= np.zeros((3,3))

#3x3 array of zeros in the center
one[1:4, 1:4] = 0

#place 9 in the center
one[2, 2] = 9

print(one)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
